/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { convertToBasic } from "../utils/material";

type GLTFResult = GLTF & {
  nodes: {
    ABOUT: THREE.Mesh;
  };
  materials: {
    ["ABOUT.MAT"]: THREE.MeshStandardMaterial;
  };
};

const GLTF_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/SpacesVR8_1-1606605325/spacesvr_08.1.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials: oldMaterials } = useGLTF(GLTF_URL) as GLTFResult;

  const materials = convertToBasic(oldMaterials);

  return (
    <group ref={group} {...props}>
      <group>
        <mesh
          material={materials["ABOUT.MAT"]}
          geometry={nodes.ABOUT.geometry}
          name="ABOUT"
          position={[6.2512, 4.17, -3.2089]}
          rotation={[0, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(GLTF_URL);
