/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";
import { DRACO_URL } from "spacesvr";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    Bonfire: THREE.Mesh;
  };
  materials: {
    ["Material #2"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/Fireplace-1607246761/BonfireFBX.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL, DRACO_URL) as GLTFResult;
  return (
    <group ref={group} {...props}>
      <group name="AuxScene">
        <group scale={[0.015, 0.015, 0.015]}>
          <mesh
            material={materials["Material #2"]}
            geometry={nodes.Bonfire.geometry}
            name="Bonfire"
            position={[0, 30.3976, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL, DRACO_URL);
