/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { convertToBasic } from "../utils/material";

type GLTFResult = GLTF & {
  nodes: {
    STRUCTURES_092: THREE.Mesh;
  };
  materials: {
    ["STRUCTURES_09.2"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/Spaces9_Buildings-1606733406/spacesvr_09.2.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials: oldMaterials } = useGLTF(
    FILE_URL,
    "https://www.gstatic.com/draco/versioned/decoders/1.4.0/"
  ) as GLTFResult;

  const materials = convertToBasic(oldMaterials);

  return (
    <group ref={group} {...props}>
      <group>
        <mesh
          castShadow
          receiveShadow
          material={materials["STRUCTURES_09.2"]}
          geometry={nodes.STRUCTURES_092.geometry}
          name="STRUCTURES_092"
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
