/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { DRACO_URL } from "spacesvr";

type GLTFResult = GLTF & {
  nodes: {
    chadlogo: THREE.Mesh;
    chadbutton: THREE.Mesh;
    chadbase: THREE.Mesh;
  };
  materials: {
    ["chad.llogo"]: THREE.MeshStandardMaterial;
    ["chad.button"]: THREE.MeshStandardMaterial;
    ["chad.base"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/CHAD-1607256005/chad.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL, DRACO_URL) as GLTFResult;
  return (
    <group ref={group} {...props}>
      <group>
        <mesh
          material={materials["chad.llogo"]}
          geometry={nodes.chadlogo.geometry}
          name="chadlogo"
          rotation={[0, 0, 0]}
        />
        <mesh
          material={materials["chad.button"]}
          geometry={nodes.chadbutton.geometry}
          name="chadbutton"
          rotation={[0, 0, 0]}
        />
        <mesh
          material={materials["chad.base"]}
          geometry={nodes.chadbase.geometry}
          name="chadbase"
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL, DRACO_URL);
