/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { convertToBasic } from "../utils/material";

type GLTFResult = GLTF & {
  nodes: {
    CONTACT: THREE.Mesh;
  };
  materials: {
    ["CONTACT.MAT"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/SpacesVR8_4-1606605669/spacesvr_08.4.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials: oldMaterials } = useGLTF(FILE_URL) as GLTFResult;

  const materials = convertToBasic(oldMaterials);

  return (
    <group ref={group} {...props}>
      <group>
        <mesh
          material={materials["CONTACT.MAT"]}
          geometry={nodes.CONTACT.geometry}
          name="CONTACT"
          position={[-0.3737, 2.7, -5.2499]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
