/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { convertToBasic } from "../utils/material";

type GLTFResult = GLTF & {
  nodes: {
    Tree: THREE.Mesh;
    Structure: THREE.Mesh;
    Desk: THREE.Mesh;
    Drafting_Table: THREE.Mesh;
    Telescope: THREE.Mesh;
    Whiteboard: THREE.Mesh;
    Nature: THREE.Mesh;
  };
  materials: {
    SpruceBranch: THREE.MeshStandardMaterial;
    Structure: THREE.MeshStandardMaterial;
    Desk: THREE.MeshStandardMaterial;
    ["Drafting Table"]: THREE.MeshStandardMaterial;
    Telescope: THREE.MeshStandardMaterial;
    Whiteboard: THREE.MeshStandardMaterial;
    Nature: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/spaces7_1-1605952298/spacesvr_07.1.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials: oldMaterials } = useGLTF(FILE_URL) as GLTFResult;

  const materials = convertToBasic(oldMaterials);

  return (
    <group ref={group} {...props}>
      <group>
        <mesh
          material={materials.SpruceBranch}
          geometry={nodes.Tree.geometry}
          name="Tree"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2, 2, 2.5]}
        />
        <mesh
          material={materials.Structure}
          geometry={nodes.Structure.geometry}
          name="Structure"
        />
        <mesh
          material={materials.Desk}
          geometry={nodes.Desk.geometry}
          name="Desk"
          rotation={[0, 0, 0]}
        />
        <mesh
          material={materials["Drafting Table"]}
          geometry={nodes.Drafting_Table.geometry}
          name="Drafting_Table"
          rotation={[0, 0, 0]}
        />
        <mesh
          material={materials.Telescope}
          geometry={nodes.Telescope.geometry}
          name="Telescope"
          rotation={[0, -Math.PI / 6, 0]}
          scale={[0.015, 0.015, 0.015]}
        />
        <mesh
          material={materials.Whiteboard}
          geometry={nodes.Whiteboard.geometry}
          name="Whiteboard"
        />
        <mesh
          material={materials.Nature}
          geometry={nodes.Nature.geometry}
          name="Nature"
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
