/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { DRACO_URL } from "spacesvr";

type GLTFResult = GLTF & {
  nodes: {
    instalogo: THREE.Mesh;
    instabutton: THREE.Mesh;
    instabase: THREE.Mesh;
  };
  materials: {
    ["insta.logo"]: THREE.MeshStandardMaterial;
    ["insta.button"]: THREE.MeshStandardMaterial;
    ["insta.base"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/Insta-1607258516/insta.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL, DRACO_URL) as GLTFResult;
  return (
    <group ref={group} {...props}>
      <group>
        <mesh
          material={materials["insta.logo"]}
          geometry={nodes.instalogo.geometry}
          name="instalogo"
        />
        <mesh
          material={materials["insta.button"]}
          geometry={nodes.instabutton.geometry}
          name="instabutton"
        />
        <mesh
          material={materials["insta.base"]}
          geometry={nodes.instabase.geometry}
          name="instabase"
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL, DRACO_URL);
