/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { DRACO_URL } from "spacesvr";

type GLTFResult = GLTF & {
  nodes: {
    maillogo: THREE.Mesh;
    mailbutton: THREE.Mesh;
    mailbase: THREE.Mesh;
  };
  materials: {
    ["mail.logo"]: THREE.MeshStandardMaterial;
    ["mail.button"]: THREE.MeshStandardMaterial;
    ["mail.base"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/Mail-1607257928/mail.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL, DRACO_URL) as GLTFResult;
  return (
    <group ref={group} {...props}>
      <group>
        <mesh
          material={materials["mail.logo"]}
          geometry={nodes.maillogo.geometry}
          name="maillogo"
        />
        <mesh
          material={materials["mail.button"]}
          geometry={nodes.mailbutton.geometry}
          name="mailbutton"
        />
        <mesh
          material={materials["mail.base"]}
          geometry={nodes.mailbase.geometry}
          name="mailbase"
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL, DRACO_URL);
