/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { DRACO_URL } from "spacesvr";

type GLTFResult = GLTF & {
  nodes: {
    portallogo: THREE.Mesh;
    portalbutton: THREE.Mesh;
    portalbase: THREE.Mesh;
  };
  materials: {
    ["portal.logo"]: THREE.MeshStandardMaterial;
    ["portal.button"]: THREE.MeshStandardMaterial;
    ["portal.base"]: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/Portal-1607255745/portal.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(FILE_URL, DRACO_URL) as GLTFResult;
  return (
    <group ref={group} {...props}>
      <group>
        <mesh
          material={materials["portal.logo"]}
          geometry={nodes.portallogo.geometry}
          name="portallogo"
          position={[0, 0, 0.0685]}
        />
        <mesh
          material={materials["portal.button"]}
          geometry={nodes.portalbutton.geometry}
          name="portalbutton"
          rotation={[0, 0, 0]}
        />
        <mesh
          material={materials["portal.base"]}
          geometry={nodes.portalbase.geometry}
          name="portalbase"
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL, DRACO_URL);
