/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { convertToBasic } from "../utils/material";

type GLTFResult = GLTF & {
  nodes: {
    ROCKS: THREE.Mesh;
  };
  materials: {
    ROCKS: THREE.MeshStandardMaterial;
  };
};

const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/Spaces9_Rocks-1606731798/spacesvr_09.1.glb";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(
    FILE_URL,
    "https://www.gstatic.com/draco/versioned/decoders/1.4.0/"
  ) as GLTFResult;

  // const materials = convertToBasic(oldMaterials)

  return (
    <group ref={group} {...props}>
      <group>
        <mesh
          castShadow
          material={materials.ROCKS}
          geometry={nodes.ROCKS.geometry}
          name="ROCKS"
        />
      </group>
    </group>
  );
}

useGLTF.preload(FILE_URL);
